version: "3.8"
services:
  production:
    container_name: doasanguepoa-front
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BASE_URL_API=http://testeurl:8081/
    ports:
      - '8080:80'

#  client:
#    stdin_open: true
#    build:
#      context: .
#      dockerfile: Dockerfile.dev
#    ports:
#      - "4000:4000"
#    volumes:
#      - "home/app/node_modules"
#      - "./:/home/app"