name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-tests-chrome-instituicao:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Runnin project
        run: npm run start &

      - name: Run Cypress tests
        run: npx cypress run --browser chrome --spec "cypress/e2e/firefox-teste-instituicao.cy.js"

  cypress-tests-chrome-usuario:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Runnin project
        run: npm run start &

      - name: Run Cypress tests
        run: npx cypress run --browser chrome --spec "cypress/e2e/firefox-teste-usuario.cy.js"
